version: "3.7"

services:
  db:
    image: postgres:15
    container_name: memes_db
    hostname: db
    command:
      - -p 2222
    expose:
      - 2222
    env_file:
      - .env
#    volumes:
#      - store-data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    container_name: memes_app
    volumes:
      - .:/app
    command: ["./app.sh"]
    ports:
      - 8002:8000
    depends_on:
      - db

#volumes:
#  store-data: